AllCops:
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 100

Lint/RaiseException:
  Enabled: True

Lint/StructNewOverride:
  Enabled: True

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  ExcludedMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define

Metrics/ClassLength:
  Max: 125

Metrics/MethodLength:
  Max: 25

Style/HashEachMethods:
  Enabled: True

Style/HashTransformKeys:
  Enabled: True

Style/HashTransformValues:
  Enabled: True
