AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  IgnoredMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define

Metrics/ClassLength:
  Max: 125

Metrics/MethodLength:
  Max: 25
